[build]
  publish = "public"
  command = "python3 -m pip install --upgrade pip && pip3 install -r requirements.txt && python3 make_sku_pages.py --csv data/skus.csv --public public && python3 build_redirects.py --csv data/skus.csv --out _redirects"

[build.environment]
  PYTHON_VERSION = "3.11"

# Si prefieres NO usar _redirects por SKU y quieres una sola regla genérica:
# [[redirects]]
#   from = "/p/:sku"
#   to = "/sku/:sku/index.html"
#   status = 200
