[build]
  publish = "public"
  command = "python3 -m pip install --upgrade pip && pip3 install -r tools/requirements.txt && python3 tools/make_sku_pages.py --csv data/skus.csv --public public"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/p/:sku"
  to = "/sku/:sku/index.html"
  status = 200
