[build]
  publish = "public"

# Reescribe /p/:sku a la p치gina est치tica correspondiente sin cambiar la URL en el navegador
[[redirects]]
  from = "/p/:sku"
  to = "/sku/:sku/index.html"
  status = 200

# Redirecciones can칩nicas opcionales (descomenta si prefieres 301 a la URL can칩nica)
# [[redirects]]
#   from = "/p/ABC123"
#   to = "/sku/ABC123/"
#   status = 301
